version: '3.9'

services:
  admin:
    build:
      context: ./client/Admins
    ports:
      - "8081:8080"
    depends_on:
      - server
    env_file:
      - .env

  customer:
    build:
      context: ./client/Customers
    ports:
      - "8082:8080"
    depends_on:
      - server
    env_file:
      - .env

  user:
    build:
      context: ./client/Users
    ports:
      - "8083:8080"
    depends_on:
      - server
    env_file:
      - .env

  server:
    build:
      context: ./server
    ports:
      - "3000:3006"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}